### ISSUE TITLE
Linux build errors

### ISSUE THREAD

**Issue by italic-r** [yantor3d/angularNodes#1]
I tried to get this going on Linux, but without success. I'm not a C programmer, so I am unable to fix this myself. I've attached a multi-threaded log.

Maya 2016.5
Centos 7
GCC 4.8.5-4

[log.txt](https://github.com/yantor3d/angularNodes/files/456422/log.txt)

**Comment by yantor3d** [comment]
Good morning,

I'm afraid the CMakeList.txt file I included is designed for Windows, not Linux. I am not very familiar with CMake in general, and don't have a Linux build myself. The best I can do is point you toward others who have, it seems, done the leg work already. 

https://github.com/nerdvegas/vfxcmake
https://github.com/chadmv/cgcmake
https://www.youtube.com/watch?v=2mUOt_F2ywo

Hopefully these resources help.

**Comment by yantor3d** [comment]
I did some work examining the CMake files I linked in my previous comment. After some trial and error I got the plugin to compile on a Linux machine running Fedora. Give it a try. Note that you'll need to have two environment variables set:

MAYA_INCLUDE_PATH (the /include directory from the devkit)
MAYA_LIBRARY_PATH (the /lib directory in your Maya install folder)

**Comment by italic-r** [comment]
That seems to have done it! I tried working cgcmake into your CmakeLists.txt, but it didn't go so well.

Thanks!
